### ISSUE TITLE
Manual failsafe

### ISSUE THREAD

**Issue by juangallostra** [simondlevy/Hackflight#16]
Hackflight already has  [failsafe](https://github.com/simondlevy/Hackflight/blob/master/src/hackflight.hpp#L127-L137) (cut motors) for when it loses R/C signal  (it works with SBUS and DSMX).

The point here is enabling the user to immediately stop the drone with, for example, a switch, if anything goes wrong.

**Comment by juangallostra** [comment]
Since it is now possible to arm and disarm via an aux switch I guess this issue can be closed. Agree @simondlevy ?

**Comment by simondlevy** [comment]
Agreed!
