### ISSUE TITLE
Butterfly board support

### ISSUE THREAD

**Issue by juangallostra** [simondlevy/Hackflight#17]
Develop the required code so that Hackflight can run on a [Butterfly board](https://www.tindie.com/products/TleraCorp/butterfly-stm32l433-development-board/?pt=ac_prod_search).

**Comment by juangallostra** [comment]
@simondlevy : Although we haven't tried yet to fly a real drone with the butterfly board I think that we can already say that Hackflight does support the butterfly board. Hence, I believe we can close this issue.

File that adds support for the butterfly board: https://github.com/simondlevy/Hackflight/blob/master/src/boards/butterfly.hpp

**Comment by simondlevy** [comment]
Reopened pending investigation of PWM output on digital pins 5,6.

**Comment by kriswiner** [comment]
Whats' the issue with 5 and 6?

**Comment by simondlevy** [comment]
By [modifying](https://github.com/simondlevy/grumpyoldpizza/blob/master/stm32l4/variants/STM32L433CC-Butterfly/variant.cpp#L48-L55) my version of STM32L4  I can now spin motors on pins 3,4,5,6.

Before closing this issue I will test SBUS receiver.

**Comment by juangallostra** [comment]
@simondlevy I guess we can close this issue now? :smiley:
