### ISSUE TITLE
HackflightSim: No hackflight.h file for DynamicsThread.cpp

### ISSUE THREAD

**Issue by NicholasQNguyen** [simondlevy/Hackflight#172]
In DynamicsThread.cpp, it includes a file called "hackflight.h." However, this file is no where in the directory.
Attached is a log of when I tried to build the project.
[HackflightSim.log](https://github.com/simondlevy/Hackflight/files/8688448/HackflightSim.log)

**Comment by simondlevy** [comment]
Thanks for catching this, Nicholas.  I've removed the stale instructions and added info on how to generate the hackflight.h file automatically using Haskell.
